-- Replica 초기화 스크립트

-- 모든 호스트에서 root 접근 허용
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '0000';
CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED BY '0000';
CREATE USER IF NOT EXISTS 'root'@'::1' IDENTIFIED BY '0000';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'::1' WITH GRANT OPTION;

FLUSH PRIVILEGES;

-- 레플리케이션은 별도 스크립트에서 설정